canonical/masterclasses.canonical.com

templates/base.html
templates/masterclasses.html
webapp/masterclasses.py

Assumption: All events start at 11 AM CET with default duration of 45 mins
Reasoning: For the sake of simplicity and because currently we don't have any "Start Time" field in the [spreadsheet](https://docs.google.com/spreadsheets/d/1fFumFWIM3oHwLr9pcBlaANcadAU0bNJxbkfGKwC_1pg/).
Possible improvements:
Replace "Date" field with "DateTime" field in the spreadsheet. This will break some internal functions that use the "Date" field to fetch previous sessions.

Add to calendar btn, favicon update and event location fix [WD-5131]

---

templates/shared/_card--masterclass.html
webapp/masterclasses.py

Introduced new "thumbnails" column in the spreadsheet which has the redesigned thumbnails uploaded on the assets.ubuntu.com CDN.
This PR fetches that thumbnails column and displays that if defined, otherwise displays the gdrive one.
The new thumbnail design looks like this:

Fetch thumbs from thumbnails column

---

templates/masterclasses.html

Now we publish events in [masterclasses calendar](https://calendar.google.com/calendar/u/0?cid=Y19iNjdjNzE1M2MzMzA4ZDM5Y2RjNzg2YjBjOWMzMDExNWY3MDg2YTc0NjQ0ZTYxYTFlZDFkYmJiYTdlOTc3YzAwQGdyb3VwLmNhbGVuZGFyLmdvb2dsZS5jb20) (only accessible inside Canonical) in favour of getting rid of the "invite-list". 
Also removed the "Location" bullet point in the upcoming sessions column, because the published event already contains google meet link.
The rationale behind using published events, is that anyone from Canonical can now record the meeting. Helps in case librarian is ooo.

Use gcal published events and removed location

---

README.md

There was not height on the image, which shifted the layout awkwardly.

Add height to readme img to prevent CLS

---

templates/masterclasses.html

Reset button only needs to appear when a topic filter chip is clicked. Currently, there was a bug where it used to show up even when no filter was chosen.

Show reset btn only when topic chip clicked

---

templates/masterclasses.html

Made the "Register your session" button a primary green button, to make it more prominent on the page.

Make Register your session btn primary btn

---

templates/masterclasses.html
webapp/masterclasses.py

- Add sprint presentations tab
- Load the sessions from the spreadsheet
Closes #36 
1. Load the demo or run this branch locally
2. See there is a new tab for sprint presentations
3. Click it, and see it replaces the content below with the only video in the sheet so far 
Fixes WD-7722

WD-7722 - Add sprint presentations tab

---

templates/masterclasses.html

Fixed a typo on the id so the sprints content is hidden when on sessions.
Open the demo
Scroll to the bottom and see there is no sprint content
Use the tabs and see if they work as expected

Fix the sprints panel

---

templates/base.html

* Added GA4 for measuring basic ways how users interact with the website.
* Created a new property under Canonical Ltd. organisation.
* Measurement ID: G-8GBDZE0HME
Followed this article for setting up GA: https://support.google.com/analytics/answer/9304153?hl=en
> Following steps can only be done after the website is live to check if GA is working as expected.
1. Sign in to your [Google Analytics account](https://analytics.google.com/).
2. Click [Admin](https://support.google.com/analytics/answer/6132368).
3. At the top of the Property column, select masterclasses.canonical.com.
4. In the Property column, click Data streams > Web.
5. Click the data stream for Masterclasses.
6. Under Google tag, click View tag instructions.
7. On the Installation instructions page, select Install manually …

Add Google Analytics tag [WD-8163]

---

templates/masterclasses.html

- Fix empty upcoming sessions column showing up.
- If no upcoming_sessions, main content takes the full grid space, i.e col-12 instead of col-9.

fix(upcoming-sessions): Hide when no upcoming sessions

---

konf/site.yaml

- Explicitly added `domain` and `tlsName` k8s ingress variables due to the unusual nature of the staging domain, `https://staging.masterclasses.canonical.com`, which is broken in `konf`
- Check that the staging sites is accessible

Explicitly define domain and tls k8s names

---

requirements.txt
webapp/app.py

* Added new Admin UI, accessible from `/admin` route.
* Functional with all the models already imported and can perform all the CRUD operations.
* Admin UI is accessible by all members with `canonical-content-people` team in LP. That is everyone in Web&Design team.
[WD-10569](https://warthogs.atlassian.net/browse/WD-10569)
[WD-10569]: https://warthogs.atlassian.net/browse/WD-10569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add new Admin UI with access control [WD-10569]

---

templates/shared/_card--masterclass.html

- Add vanilla external link icon to slide for better visibility 
- Also makes it easier differentiating from the card title and slide link.

Add link icon to slide link

---

konf/site.yaml

- The site.yaml contained wrong value for tlsName. Checked the secret in staging k8s cluster and updated it with the correct one.

fix(jenkins) Update tlsName for staging in site.yaml

---

webapp/admin.py

Unsure when, but I removed the text area when testing and never added it back. This merge changes the text area of the flask admin video descriptions to allow for easier multiline MD editing.

Added back markdown text area to flask_admin view.

---

package.json
src/styles.scss

- silences unnecessary sass warnings from Vanilla codebase
- drive-by: removes unnecessary icon imports
- Check out this feature branch
- Run command `dotrun build-css`
- There should be no warnings from sass build in the output
- Or check the [CI output](https://github.com/canonical/masterclasses.canonical.com/actions/runs/14034117293/job/39288101610?pr=73#step:7:347)

Silence sass warnings from Vanilla

---

templates/base.html
templates/masterclasses.html
templates/register.html
templates/video_player.html
templates/videos.html

- Moves `main` element to correctly wrap main content only
- Uses Vanilla site layout with sticky footer and paper background'
- Removes unnecessary usage of sliding navigation (and simplifies the JS handling of navigation on mobile)
- Doing some small changes in content templates to accommodate that (removing bordered strip)
- Drive-by: fix "Register an idea" button on home page to link to form instead of discourse
- Check home page on demo: https://masterclasses-canonical-com-74.demos.haus/
- Make sure it looks OK
- Go to small screen, make sure you can open navigation and it works as expected
- Check other views: [videos](https://masterclasses-canonical-com-74.demos.haus/videos), [video](https://masterclasses-canonical-com-74.demos.haus/videos/analytics-guide-securing-docker-design-expl …

Base template improvements

---

templates/masterclasses.html

- Fixes a but with heading appearing even if there are no upcoming sessions
- Check out this feature branch
- Run the site using the command `dotrun`
- Remove upcoming sessions from db or add `{% set upcoming = [] %}` in line 56 of `masterclasses.html` to fake empty data
- Go to home page and see if it renders as expected
After fix:
[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

Fix empty upcoming on home page

---

templates/masterclasses.html

- Adds a section with recent sprints (Engineering and Roadmap) to home page.
- This is currently manually maintained
- Check out this feature branch
- Run the site using the command `dotrun`
- Open home page: https://masterclasses-canonical-com-80.demos.haus/
- Check the new "Recent Sprints" section
- Click on "Explore …" links
- NOTE: those links will not show actual videos from sprints (we don't have them in demo server), but URL should have correct filters reflected in query params
Fixes WD-22172
[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

Add recent sprints to home page

---

templates/masterclasses.html

Adds current Berlin Commercial sprint on the home page
Demos are failing unfortunately, so it needs to be QA'ed locally.
- Check out this feature branch
- Run the site using the command `dotrun` (see README for running database)
- View the site locally in your web browser at: http://0.0.0.0:8409/
- Be sure to test on mobile, tablet and desktop screen sizes
- Check newly added Comercial Sprint on home page
[QA steps](https://discourse.canonical.com/t/qa-steps/152) - [Commit guidelines](https://discourse.canonical.com/t/commit-guidelines/148)

Add Berlin Commercial Sprint to home page
